package types

// Code generated by centrifuge. DO NOT EDIT.

type OTelGRPC struct {
	Endpoint string            `json:"endpoint,omitempty"`
	Insecure bool              `json:"insecure,omitempty"`
	TLS      *ClientTLS        `json:"tls,omitempty"`
	Headers  map[string]string `json:"headers,omitempty"`
}

type OTelHTTP struct {
	Endpoint string            `json:"endpoint,omitempty"`
	TLS      *ClientTLS        `json:"tls,omitempty"`
	Headers  map[string]string `json:"headers,omitempty"`
}
