package types

// Code generated by centrifuge. DO NOT EDIT.

type OTelTracing struct {
	GRPC *OTelGRPC `json:"grpc,omitempty" label:"allowEmpty"`
	HTTP *OTelHTTP `json:"http,omitempty" label:"allowEmpty"`
}

type TracingVerbosity string
